"""initial schema

Revision ID: 8307188288d4
Revises: 
Create Date: 2025-04-24 20:41:39.889555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8307188288d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrobbles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(length=350), nullable=False),
    sa.Column('album_title', sa.String(length=350), nullable=False),
    sa.Column('track_title', sa.String(length=350), nullable=False),
    sa.Column('play_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_name', 'track_title', 'play_time', name='uq_scrobble')
    )
    op.create_index(op.f('ix_scrobbles_play_time'), 'scrobbles', ['play_time'], unique=False)
    op.create_table('user_country',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.CheckConstraint('(end_date IS NULL) OR (end_date > start_date)', name='ck_usercountry_period_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_name', 'start_date', name='uq_usercountry_start')
    )
    op.drop_table('scrobbles_20250416_092319')
    op.drop_table('scrobbles_20250422_221543')
    op.drop_table('ascii_chars')
    op.drop_table('scrobbles_20250416_100015')
    op.alter_column('artist_variants_canonized', 'comment',
               existing_type=mysql.VARCHAR(length=1008),
               type_=sa.String(length=750),
               existing_nullable=True)
    op.alter_column('artistcountry', 'artist_name',
               existing_type=mysql.VARCHAR(length=1008),
               type_=sa.String(length=750),
               existing_nullable=False)
    op.create_index(op.f('ix_artistcountry_artist_name'), 'artistcountry', ['artist_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artistcountry_artist_name'), table_name='artistcountry')
    op.alter_column('artistcountry', 'artist_name',
               existing_type=sa.String(length=750),
               type_=mysql.VARCHAR(length=1008),
               existing_nullable=False)
    op.alter_column('artist_variants_canonized', 'comment',
               existing_type=sa.String(length=750),
               type_=mysql.VARCHAR(length=1008),
               existing_nullable=True)
    op.create_table('scrobbles_20250416_100015',
    sa.Column('artist_name', mysql.VARCHAR(length=2550), nullable=True),
    sa.Column('album_name', mysql.VARCHAR(length=2550), nullable=True),
    sa.Column('track_name', mysql.VARCHAR(length=2550), nullable=True),
    sa.Column('play_time', mysql.DATETIME(), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ascii_chars',
    sa.Column('ascii_code', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ascii_char', mysql.CHAR(length=1), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('scrobbles_20250422_221543',
    sa.Column('artist_name', mysql.VARCHAR(length=2550), nullable=True),
    sa.Column('album_name', mysql.VARCHAR(length=2550), nullable=True),
    sa.Column('track_name', mysql.VARCHAR(length=2550), nullable=True),
    sa.Column('play_time', mysql.DATETIME(), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('scrobbles_20250416_092319',
    sa.Column('artist_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('album_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('track_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('play_time', mysql.DATETIME(), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_country')
    op.drop_index(op.f('ix_scrobbles_play_time'), table_name='scrobbles')
    op.drop_table('scrobbles')
    # ### end Alembic commands ###
