"""tz aware play_time

Revision ID: 840464d5070e
Revises: 8307188288d4
Create Date: 2025-04-25 17:31:12.965010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '840464d5070e'
down_revision: Union[str, None] = '8307188288d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrobbles_20250424_210834')
    op.drop_table('scrobbles_20250424_192037')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrobbles_20250424_192037',
    sa.Column('Artist', mysql.TEXT(), nullable=True),
    sa.Column('Song', mysql.TEXT(), nullable=True),
    sa.Column('Album', mysql.TEXT(), nullable=True),
    sa.Column('Timestamp', mysql.TEXT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('scrobbles_20250424_210834',
    sa.Column('Artist', mysql.TEXT(), nullable=True),
    sa.Column('Song', mysql.TEXT(), nullable=True),
    sa.Column('Album', mysql.TEXT(), nullable=True),
    sa.Column('Timestamp', mysql.TEXT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
